### ISSUE TITLE
黑暗模式下，搜索框结果背景依然为白色，造成文字辨识困难

### ISSUE THREAD

**Issue by jerrylususu** [SUSTC/sustech-online-ng#12]
见图左侧
![image](https://user-images.githubusercontent.com/17522475/95833542-5e9f6480-0d6e-11eb-99fb-165727e282c3.png)

**Comment by liziwl** [comment]
应该是要调一下，可能是这里加颜色模板没有支持搜索框的 https://github.com/SUSTC/sustech-online-ng/commit/f84e9def5cecbbcd7306e019e424f4cd91d00972

**Comment by jerrylususu** [comment]
devtool 看了一下，似乎是 .page-title 有一个 CSS `background` 属性被设定了。取消勾选后显示正常
![image](https://user-images.githubusercontent.com/17522475/95856982-7cc88d00-0d8d-11eb-95fe-420741c3b8da.png)

![image](https://user-images.githubusercontent.com/17522475/95856987-80f4aa80-0d8d-11eb-913c-b40f8ff12048.png)

**Comment by sparkcyf** [comment]
> devtool 看了一下，似乎是 .page-title 有一个 CSS `background` 属性被设定了。取消勾选后显示正常
> ![image](https://user-images.githubusercontent.com/17522475/95856982-7cc88d00-0d8d-11eb-95fe-420741c3b8da.png)
> 
> ![image](https://user-images.githubusercontent.com/17522475/95856987-80f4aa80-0d8d-11eb-913c-b40f8ff12048.png)

当时图方便，是直接用了这个插件： https://github.com/tolking/vuepress-theme-default-prefers-color-scheme/ 估计需要给他们提个PR了。
