### ISSUE TITLE
移动设备搜索框宽度超出 viewpoint

### ISSUE THREAD

**Issue by jerrylususu** [SUSTC/sustech-online-ng#15]
注：**无法**通过双指缩放缩小至可以看到分类的大小
![image](https://user-images.githubusercontent.com/17522475/99395570-98d6c580-291b-11eb-9574-dd14ac470189.png)

**Comment by liziwl** [comment]
![image](https://user-images.githubusercontent.com/23000702/99413553-dc87fa00-2930-11eb-847f-fa85f09ad3ca.png)

电脑端貌似体验变差了，还需要改一下。
