### ISSUE TITLE
Vuepress 更新至2.0

### ISSUE THREAD

**Issue by liziwl** [SUSTC/sustech-online-ng#29]
## 参考文档

https://vuepress2.netlify.app/guide/migration.html

https://github.com/vuepress/vuepress-next

**Comment by liziwl** [comment]
兼容性和插件更新的问题需要同步检查

**Comment by liziwl** [comment]
尝试部署在 vuepress2 的分支上。@sparkcyf 帮忙一起看看吧

在 vuepress2 部署，目前已经遇到的问题：

- [ ] 插件暂时未迁移，需要检查兼容性
- [ ] 如果 img 的 HTML 标签方式引用图片，似乎会丢失引用。需要测试在什么情况下会丢失引用。
- [ ] 搜索插件的部署：检查是否能全文搜索
- [ ] 上一版本直接在文中写JS脚本的方式可能无效了，编译打包后直接丢失了 `<script>...</script>` 的代码

**Comment by sparkcyf** [comment]
> 尝试部署在 vuepress2 的分支上。@sparkcyf 帮忙一起看看吧
> 
> 在 vuepress2 部署，目前已经遇到的问题：
> 
> * [x]  插件暂时未迁移，需要检查兼容性
> * [ ]  如果 img 的 HTML 标签方式引用图片，似乎会丢失引用。需要测试在什么情况下会丢失引用。
> * [x]  搜索插件的部署：检查是否能全文搜索
> * [ ]  上一版本直接在文中写JS脚本的方式可能无效了，编译打包后直接丢失了 `<script>...</script>` 的代码

- 搜索插件已经改为使用 algolia docsearch （in https://github.com/SUSTC/sustech-online-ng/commit/95337b76f6e73bf89aa173fd19af81c9aa293467 ）
- 现有插件已经基本完成迁移（in https://github.com/SUSTC/sustech-online-ng/commit/9cbf574ec72f5942ee5a9a17e85d309bfafe1930 & https://github.com/SUSTC/sustech-online-ng/commit/862d1f3619d276e3eb4f9a08302ee4613b338415 ）

**Comment by sparkcyf** [comment]
fixed in https://github.com/SUSTC/sustech-online-ng/commit/95c9016c8394b7277feaa4e06bc6147380aff222

先持续观察一周手册里面还有没有图片和文字异常的情况，再关闭此issue。

**Comment by liziwl** [comment]
似乎没有问题，关闭了。
