### ISSUE TITLE
从`网络与信息中心`页面跳转到`远程桌面`页面时出现404

### ISSUE THREAD

**Issue by lethal233** [SUSTC/sustech-online-ng#46]
由该页面点击跳转
![image](https://user-images.githubusercontent.com/47763046/124340013-c2abd680-dbe4-11eb-99f4-3fece978f0d5.png)
出现404
![image](https://user-images.githubusercontent.com/47763046/124340027-df480e80-dbe4-11eb-9b1e-d4be7f905a0f.png)
但fork到本地之后测试正常
![image](https://user-images.githubusercontent.com/47763046/124340044-0272be00-dbe5-11eb-9d63-27cf356e264f.png)

**Comment by sparkcyf** [comment]
这边看起来没有问题，有尝试过使用隐身窗口和其他浏览器来复现这个问题吗？

https://user-images.githubusercontent.com/14960340/124340124-8167f680-dbe5-11eb-9251-4d6a421df3c6.mov

**Comment by lethal233** [comment]
> 这边看起来没有问题，有尝试过使用隐身窗口和其他浏览器来复现这个问题吗？
> 
>  Screen.Recording.2021-07-03.at.10.00.21.AM.mov 
> may related to #29

很奇怪，我这台电脑用chrome和firefox点开网页都是404

**Comment by liziwl** [comment]
❌ https://sustech.online/service/network/remote-desktop/

✅ https://sustech.online/service/remote-desktop/

**Comment by lethal233** [comment]
@liziwl @sparkcyf 谢谢，现在再打开问题解决了【捂脸】，关闭此issue了。

**Comment by liziwl** [comment]
![telegram-cloud-photo-size-5-6269562378895076560-y](https://user-images.githubusercontent.com/23000702/124341117-cd6a6980-dbec-11eb-969b-ac4a8858c5a4.jpg)

**Comment by lethal233** [comment]
@liziwl 我这边测试的行为跟你的行为一样
sustech.online:
![image](https://user-images.githubusercontent.com/47763046/124346186-0831c900-dc10-11eb-96bd-949b549f0ad6.png)
netlify
![image](https://user-images.githubusercontent.com/47763046/124346232-4f1fbe80-dc10-11eb-9902-f9b8f22fbbbc.png)

**Comment by liziwl** [comment]
提供一下境外的链接：https://sustech-book.netlify.app/service/network/

**Comment by liziwl** [comment]
可能是阿里云对象存储有点问题，还在沟通中。https://github.com/SUSTC/sustech-online-ng/commit/02e6a70395eb2c9348f75e606fa1a03befabbea2 中已经更新至腾讯云的服务。

**Comment by liziwl** [comment]
目前似乎已经解决，阿里云也修复了，由于服务价格相同懒得切回阿里云，仅当作温备份。
