### ISSUE TITLE
`Ehall`标签下面学校简称更正

### ISSUE THREAD

**Issue by lethal233** [SUSTC/sustech-online-ng#47]
![image](https://user-images.githubusercontent.com/47763046/124340171-cf7cfa00-dbe5-11eb-86bf-cf4c297d17a7.png)

**Comment by lethal233** [comment]
需要更新的话我提一个pr，不用更新的话可以删除此issue

**Comment by sparkcyf** [comment]
> 需要更新的话我可以提一个pr，不用更新的话可以删除此issue

欢迎PR～
