### ISSUE TITLE
建议改进对校园巴士线路的描述

### ISSUE THREAD

**Issue by Fros1er** [SUSTC/sustech-online-ng#5]
原来没看懂双向箭头的含义，直到今天背着一堆书坐巴士在创园那边转了一圈又回到了原地。。。
建议把路线写详细点并且特别标注一下绕的那一圈
（我现在也没完全看懂orz，怕自己写会出问题

**Comment by sparkcyf** [comment]
我有空制作一个类似地铁的线路图。但由于不知道学校最终会怎么改线，估计要等到学校九月初更改校巴线路之后才能做。

**Comment by liziwl** [comment]
做个一行的那种线路图可能好点，当时偷懒了，写的文字版😂

**Comment by liziwl** [comment]
![未标题-3](https://user-images.githubusercontent.com/23000702/92221396-fdaf8180-eecf-11ea-966b-26f227301806.png)

做了个车厢版本的，有没有什么要改的地方。

**Comment by Fros1er** [comment]
感觉有点歧义...看起来是科研楼→欣园不经过创园，而反过来每站都经过的样子

**Comment by liziwl** [comment]
这个单行表示有点麻烦，科研楼→欣园是要走个圈，反过来不用。

**Comment by Fros1er** [comment]
也就是说

* 上行
宿舍→荔园→慧园→创园→荔园→慧园→欣园
* 下行
欣园→慧园→创园→荔园→宿舍

这样？
我觉得可以把圆换成长方形，然后上下行用两种颜色的线和箭头表示。

**Comment by liziwl** [comment]
![巴士2](https://user-images.githubusercontent.com/23000702/92297228-ae209280-ef6f-11ea-9205-ae6c73adf101.png)
这样咋样

**Comment by Fros1er** [comment]
![23EDEA09-F0EF-4C5D-9B45-1A980E3A692D](https://user-images.githubusercontent.com/34234343/92298922-69512780-ef80-11ea-82da-58e04e0d96e0.png)
或许这样能清楚点
（图画的有点草。。。

**Comment by liziwl** [comment]
感觉两行再加字太多了，想一行解决。

![巴士2](https://user-images.githubusercontent.com/23000702/92301515-1040be00-ef97-11ea-965d-d3237f81569a.png)

**Comment by sparkcyf** [comment]
> 感觉两行再加字太多了，想一行解决。
> 
> ![巴士2](https://user-images.githubusercontent.com/23000702/92301515-1040be00-ef97-11ea-965d-d3237f81569a.png)

话说要不把高峰线不停的站的站点符号改成源泉，这样可以更好的表示“不停车”

**Comment by Fros1er** [comment]
> > 感觉两行再加字太多了，想一行解决。
> > ![巴士2](https://user-images.githubusercontent.com/23000702/92301515-1040be00-ef97-11ea-965d-d3237f81569a.png)
> 
> 话说要不把高峰线不停的站的站点符号改成圆圈，这样可以更好的表示“不停车”

我觉得改符号没问题...如果要一行解决的话我也想不出更清楚的画法，感觉只能文字说明了

**Comment by sparkcyf** [comment]
昨天我咨询了一下管理校巴的老师，新的线路图就不会在创园和荔园之间绕圈了，新的图大概是这样：
![image](https://user-images.githubusercontent.com/14960340/92316966-cce55e80-f02d-11ea-8f7b-6e7bedfbe56d.png)

我按照新的线路图改了一个：

![system-map-202009-1](https://user-images.githubusercontent.com/14960340/92316971-dec70180-f02d-11ea-928a-4032b0ad22b2.jpg)

**Comment by sparkcyf** [comment]
尝试于 https://github.com/SUSTC/sustech-online-ng/commit/8c216da3f0538103cc0005d584be07929d6661e7 进行改进

**Comment by Fros1er** [comment]
😂那就没问题了
之前那个线路是真的难搞.......

**Comment by sparkcyf** [comment]
管理校巴的老师表示绕圈的情况还是会出现，这个issue可能还需要继续讨论一下。

**Comment by liziwl** [comment]
又得改图了，高峰线不停一号门，改行政楼。国庆或者周末去改图。

**Comment by jerrylususu** [comment]
一个诡异的 proposal
![image](https://user-images.githubusercontent.com/17522475/95471676-c7748e80-09b4-11eb-886f-ea84b7a4c392.png)

**Comment by liziwl** [comment]
基本解决
