### ISSUE TITLE
链接有效性检查

### ISSUE THREAD

**Issue by liziwl** [SUSTC/sustech-online-ng#51]
md形式的链接从根开始必须以/开头，不然默认是当前路径。

已知有问题
- [x] 迎新页面 docs/if-you-are-a-freshman/README.md

**Comment by liziwl** [comment]
检查工具

https://www.deadlinkchecker.com/

**Comment by liziwl** [comment]
![网页捕获_10-7-2021_112345_](https://user-images.githubusercontent.com/23000702/125150298-547d8b80-e171-11eb-83bf-58da48489b66.jpeg)

**Comment by liziwl** [comment]
https://assets.sustech.online/documents/本科人才培养方案/2018级本科生培养方案（适用于第二学年结束时，申请进入专业）/ | 2018级(第二学年结束时进入专业)open in new window | https://sustech.online/study/
-- | -- | --


http://www.nic.edu.cn/member-cgi/i6obj?query=SUSTC6-CERNET2 | SUSTC6-CERNET2open in new window | https://sustech.online/service/network/
-- | -- | --

**Comment by liziwl** [comment]
https://github.com/SUSTC/sustech-online-ng/commit/e779f8e0acb9cf7780747db3c7039a05d31480bb 修复部分链接

**Comment by sparkcyf** [comment]
> [https://assets.sustech.online/documents/本科人才培养方案/2018级本科生培养方案（适用于第二学年结束时，申请进入专业）/](https://assets.sustech.online/documents/%E6%9C%AC%E7%A7%91%E4%BA%BA%E6%89%8D%E5%9F%B9%E5%85%BB%E6%96%B9%E6%A1%88/2018%E7%BA%A7%E6%9C%AC%E7%A7%91%E7%94%9F%E5%9F%B9%E5%85%BB%E6%96%B9%E6%A1%88%EF%BC%88%E9%80%82%E7%94%A8%E4%BA%8E%E7%AC%AC%E4%BA%8C%E5%AD%A6%E5%B9%B4%E7%BB%93%E6%9D%9F%E6%97%B6%EF%BC%8C%E7%94%B3%E8%AF%B7%E8%BF%9B%E5%85%A5%E4%B8%93%E4%B8%9A%EF%BC%89/)	2018级(第二学年结束时进入专业)open in new window	https://sustech.online/study/
> http://www.nic.edu.cn/member-cgi/i6obj?query=SUSTC6-CERNET2	SUSTC6-CERNET2open in new window	https://sustech.online/service/network/
> @sparkcyf 这两个需要你看看能不能修

nic这个只有在教育网才能访问，另一个我改天换一下存储商。

**Comment by liziwl** [comment]
![www deadlinkchecker com_website-dead-link-checker asp](https://user-images.githubusercontent.com/23000702/125189785-74de4080-e26c-11eb-997a-75df74274c70.png)

**Comment by liziwl** [comment]
社团页面的列表跳转有问题

**Comment by liziwl** [comment]
> 社团页面的列表跳转有问题
已解决 https://github.com/SUSTC/sustech-online-ng/commit/d862e2ded3e9819158c5cd949358224e6fdcd138
