### ISSUE TITLE
巴士时间戳不同步的问题

### ISSUE THREAD

**Issue by Donaar-dev** [SUSTC/sustech-online-ng#65]
原因：手机网页后台运行时，js会暂停

定位：

https://github.com/SUSTC/sustech-online-ng/blob/d0e7203d786ff978003f21c60aacc3140babf7a9/docs/.vuepress/components/BusTimer.vue#L90-L93

解决方式：

https://segmentfault.com/q/1010000011916121

https://www.jianshu.com/p/b417a2d4194b

**Comment by liziwl** [comment]
close at https://github.com/SUSTC/sustech-online-ng/commit/2a8d0392b68082aa64690667bc9ea33daa8b52da
